# Generated by Django 2.2.10 on 2020-05-12 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='use',
            new_name='user',
        ),
    ]
